# recipe.yaml

schema_version: 1

context:
  version: 0.1.6
  name: grikod3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org{{ name }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6c7169b6a987f3e7af4bdf569a288587f2d83aeb6f83f0e080783f46f4d95844

build:
  number: 1
  script: python -m pip install --no-deps --no-build-isolation --ignore-installed .

# 🌍 Paketinizin derleneceği tüm platformları buraya ekliyoruz:
# (Linux, Windows, macOS Intel ve macOS Apple Silicon)
build_platform:
  - linux-64
  - win-64
  - osx-64
  - osx-arm64

requirements:
  build:
    - ${{ compiler('c') }} # İşletim sistemine göre doğru C derleyicisini (GCC, MSVC, Clang) otomatik seçer
  host:
    - python >=3.11
    - pip
    - setuptools >=61.0
    - cython >=3.0.0
    - wheel
    - numpy
  run:
    - python >=3.11
    - numpy

about:
  homepage: https://github.com
  license: AGPL-3.0-or-later
  summary: 'grikod3'
  repository: https://github.com

extra:
  recipe-maintainers:
    - bilgi

