# recipe.yaml

schema_version: 1

context:
  version: 0.1.6
  name: grikod3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6c7169b6a987f3e7af4bdf569a288587f2d83aeb6f83f0e080783f46f4d95844

build:
  number: 1
  # --no-build-isolation parametresini ekleyerek 'setuptools' bulunamadı hatasını KESİNLİKLE çözüyoruz.
  # Çünkü bağımlılıkları host altından almasını zorunlu kılıyoruz.
  script: python -m pip install --no-deps --no-build-isolation --ignore-installed .
  # !!! noarch: python SATIRI BURADAN SİLİNDİ (Çünkü Cython/C içeriyor)

requirements:
  build:
    - ${{ compiler('c') }}      # Linux'ta GCC derleyicisini kurar (Cython için şart)
  host:
    - python >=3.11
    - pip
    - setuptools >=61.0
    - cython >=3.0.0            # Derleme anında setuptools'un Cython'u görmesini sağlar
    - wheel
    - numpy                     # Cython başlık dosyaları (headers) için numpy host'ta olmalı
  run:
    - python >=3.11
    - numpy

about:
  homepage: https://github.com/WhiteSymmetry/grikod3/
  license: AGPL-3.0-or-later    # pyproject.toml ile eşitledik
  summary: 'grikod3'
  repository: https://github.com/WhiteSymmetry/grikod3/

extra:
  recipe-maintainers:
    - bilgi
