name: Build wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-* cp314-* cp315-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS: auto64

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
