name: Publish to PyPI-Resmî

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v4.1.0
        env:
          CIBW_BUILD: "cp314-* cp315-*"
          CIBW_ENABLE: "cpython-prerelease"   # 3.14, 3.15 için
          CIBW_ARCHS: "auto64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist

      - name: Flatten wheel files to dist/
        run: |
          find dist -name "*.whl" -exec mv -v {} dist/ \;
          find dist -type d -empty -delete
          ls -la dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          packages-dir: dist/
